export const CREATE_PROCESSING = 'CREATE_PROCESSING';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_FAILURE';
export const CREATE_ERROR_CLEARED = 'CREATE_ERROR_CLEARED';
