export const DASHBOARD_PROCESSING = 'DASHBOARD_PROCESSING';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';
export const DASHBOARD_ERROR_CLEARED = 'DASHBOARD_ERROR_CLEARED';
