export const SIGNUP_PROCESSING = 'SIGNUP_PROCESSING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_ERROR_CLEARED = 'SIGNUP_ERROR_CLEARED';
